# prefix を Ctrl-a に変更
set -g prefix C-a
unbind C-b
bind C-a send-prefix

# ウィンドウ・ペイン番号を1始まりに
set -g base-index 1
setw -g pane-base-index 1

# ウィンドウを閉じたら番号を詰める
set -g renumber-windows on

# マウス操作を有効化
set -g mouse on

# セッション操作
bind S choose-tree -s
bind N command-prompt -p "new session:" "new-session -s '%%'"

# ウィンドウ操作
bind t new-window -c "#{pane_current_path}"
bind v copy-mode
bind p paste-buffer
bind L next-window
bind H previous-window

# ペイン分割
bind V split-window -h -c "#{pane_current_path}"
bind s split-window -v -c "#{pane_current_path}"

# ペイン移動
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# vi-modeを有効化
setw -g mode-keys vi

# コピーモードでの操作をVimライクに
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi V send -X select-line
bind -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"
bind -T copy-mode-vi Escape send -X cancel

